### ISSUE TITLE
Open source license required for use beyond The Guardian

### ISSUE THREAD

**Issue by riordan** [guardian/google-search-indexing-observatory#6]
Thank you for building and releasing Orphan; I can attest that it fills a need at newsrooms all over.

I'd love to use The Observatory for @phillymedia, but we can't use it without an open source license as an explicit part of the project. Without saying what we're allowed to do with it, we can't know our rights as users. Meanwhile setting a license can make explicit the relationship between The Guardian and any users (so an angry user can't just send their lawyers at you if they can't use it properly).

For a good background on why license your public code, I'm a fan of [The Open Source Guide: The Legal Side of Open Source](https://opensource.guide/legal/) and the [Choose a License](https://choosealicense.com) guide to license selection, but you should work with your organization to make the right selection for The Guardian. It seems like you've licensed several other popular repositories under Apache-2, which is a genuinely great license for permissive use and indemnification.

**Comment by rtyley** [comment]
Cheers @riordan , I've added the Apache v2 license, which as you say, we use a lot at the Guardian.

Good luck with using the observatory! As you might expect, we haven't specifically done a lot of work on it to make it easy to run for other organisations, but so long as you have both an AWS account for the DynamoDB table, and Google creds, you should be able to get it running.
